name: flutter_postgres
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  postgres_flutter: ^2.5.4
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
