(defun main ()
  (let ((debug (sb-ext:posix-getenv "DEBUG")))
    (if (and debug (string= debug "1"))
        (format t "test ... ok~%")
        (let ((red "\x1b[31m")
              (green "\x1b[32m")
              (blue "\x1b[34m")
              (reset "\x1b[0m"))
          (loop for i from 1 to 100 do
            (cond ((= 0 (mod i 15)) (format t "~aFizzBuzz~a~%" red reset))
                  ((= 0 (mod i 3)) (format t "~aFizz~a~%" green reset))
                  ((= 0 (mod i 5)) (format t "~aBuzz~a~%" blue reset))
                  (t (format t "~a~%" i))))))))
(main)
