import Config
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
config :phoenix_app, PhoenixAppWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

config :phoenix_app, PhoenixAppWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

config :logger, level: :info
