/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */
import { BaseModel, column } from "@adonisjs/lucid/orm";
import type { DateTime } from "luxon";
export class UserSchema extends BaseModel {
  static $columns = [
    "createdAt",
    "email",
    "id",
    "password",
    "updatedAt",
    "username",
  ] as const;
  $columns = UserSchema.$columns;
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime;
  @column()
  declare email: string;
  @column({ isPrimary: true })
  declare id: number;
  @column()
  declare password: string;
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime;
  @column()
  declare username: string;
}
