/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */
export const controllers = {
  Health: () => import("#controllers/health_controller"),
  Users: () => import("#controllers/users_controller"),
};
