(define RED "\x1b[31m")
(define GREEN "\x1b[32m")
(define BLUE "\x1b[34m")
(define RESET "\x1b[0m")
(define (run-tests)
  (if (= (+ 1 1) 2)
      (display "test ... ok\n")
      (begin (display "test ... failed\n") (exit 1))))
(define (fizzbuzz i)
  (cond
    ((= 0 (remainder i 15)) (display (string-append RED "FizzBuzz" RESET "\n")))
    ((= 0 (remainder i 3))  (display (string-append GREEN "Fizz" RESET "\n")))
    ((= 0 (remainder i 5))  (display (string-append BLUE "Buzz" RESET "\n")))
    (else                   (begin (display i) (newline)))))
(let ((debug (getenv "DEBUG")))
  (if (equal? debug "1")
      (run-tests)
      (do ((i 1 (+ i 1)))
          ((> i 100))
        (fizzbuzz i))))
