#lang racket/base
(require racket/system)
(define (run-tests)
  (if (= (+ 1 1) 2)
      (displayln "test ... ok")
      (begin (displayln "test ... failed") (exit 1))))
(let ([debug (getenv "DEBUG")])
  (if (and debug (string=? debug "1"))
      (run-tests)
      (displayln "Hello World")))
